SET @@session.time_zone = '+00:00';

-- Crear tabla EMPLEADOS

CREATE TABLE EMPLEADO (
  ID INT AUTO_INCREMENT,
  DNI VARCHAR(9) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  APELLIDOS VARCHAR(100) NOT NULL,
  DEPARTAMENTO VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(6) NOT NULL,
  CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID),
  CONSTRAINT UK_DNI UNIQUE (DNI),

);

-- Insertar registros en EMPLEADO

INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('55555555Z','Jose','perez','Empleados','123456');
INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('11111111Z','Manuel','Moreno','Empleado','123456');
INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('22222222P','María','Del monte','Empleado','123456');


-- Crear tabla ENTRADA

CREATE TABLE ENTRADA (
    ID_EMPLEADO INT NOT NULL,
    ENTRADA DATETIME NOT NULL,
    PRIMARY KEY (ID_EMPLEADO, ENTRADA),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID)
);


-- Crear tabla SALIDA

CREATE TABLE SALIDA (
    ID_EMPLEADO INT NOT NULL,
    SALIDA DATETIME NOT NULL,
    PRIMARY KEY (ID_EMPLEADO, SALIDA),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID)
);
