ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

CREATE TABLE EMPLEADO (
ID NUMBER GENERATED ALWAYS AS IDENTITY,
DNI NVARCHAR2(9) NOT NULL,
NOMBRE NVARCHAR2(100) NOT NULL,
APELLIDOS NVARCHAR2(100) NOT NULL,
DEPARTAMENTO NVARCHAR2(50) NOT NULL,
PASSWORD NVARCHAR2(6) NOT NULL,
CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID),
CONSTRAINT UK_DNI UNIQUE (DNI),
CONSTRAINT UK_PASSWORD UNIQUE (PASSWORD)
);
INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('55555555Z','RAMON','HERRAEZ','ADMINISTRADOR','123456');
INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('15555555Z','IVAN','AVILA','GESTOR','223456');
INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('25555555Z','LEO','DEL SORDO','EMPLEADO','323456');
INSERT INTO EMPLEADO (DNI,NOMBRE,APELLIDOS,DEPARTAMENTO,PASSWORD)VALUES('35555555Z','LUIGI','DEL SORDO','RESPONSABLE','423456');

CREATE TABLE ENTRADA(
ID_EMPLEADO NUMBER,
ENTRADA NVARCHAR2(50),
CONSTRAINT fk_ENTRADA_EMPLEADO FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID)
);

CREATE TABLE SALIDA(
ID_EMPLEADO NUMBER,
SALIDA NVARCHAR2(50),
CONSTRAINT fk_SALIDA_EMPLEADO FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID)
);

--DROP TABLE ENTRADA;
--DROP TABLE EMPLEADO CASCADE CONSTRAINT;
--DROP TABLE SALIDA;